### ISSUE TITLE
Feature also possible for listview

### ISSUE THREAD

**Issue by greenlevel** [NicoHaase/ea-reproducer-4293#1]
Hi,
Thanks for the feature, it's nice to have this.

I am also interested to sort the list view with a drag and drop option.
I think should be used with the batch action.

I am checking out the easyadmin 3 how to make this work. Are you also planning to make something like this?

**Comment by NicoHaase** [comment]
No, sorry, I don't plan to do this. But it should not be too difficult to build it, as soon as my MR is accepted.

Please post this as a feature request on https://github.com/EasyCorp/EasyAdminBundle/issues/
